apiVersion: apps/v1
kind: Deployment
metadata:
  name: oblik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oblik
  template:
    metadata:
      labels:
        app: oblik
    spec:
      serviceAccountName: oblik-operator
      containers:
        - name: oblik
          image: "{{ .Values.image.repository }}:{{ or .Values.image.tag "latest" }}"
          {{ if .Values.image.pullPolicy }}
          imagePullPolicy: "{{ .Values.image.tag }}"
          {{ else if .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          {{ else }}
          imagePullPolicy: Always
          {{ end }}
          ports:
            - containerPort: 9443
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{ if .Values.existingSecret }}
          envFrom:
            - secretRef:
                  name: {{.Values.existingSecret }}
          {{ end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
