apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oblikpodautoscalers.socialgouv.io
spec:
  group: socialgouv.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                defaultLimit:
                  type: boolean
                  default: true
                enforceLimit:
                  type: boolean
                  default: false
                limitRatio:
                  type: object
                  default: {}
                  properties:
                    cpu:
                      type: integer
                      default: 1
                    memory:
                      type: integer
                      default: 1
                minReplicas:
                  type: integer
                  default: 2
                baseResource:
                  type: object
                  properties:
                    cpu:
                      type: string
                      default: "0m"
                    memory:
                      type: string
                      default: "0Mi"
                cursorMode:
                  type: string
                  enum: ["all", "any"]
                  default: "any"
                podCursor:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                containerCursors:
                  type: array
                  items:
                    type: object
                    properties:
                      containerName:
                        type: string
                      cpu:
                        type: string
                      memory:
                        type: string
                targetRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                hpa:
                  type: object
                  description: "Embedded full spec of Horizontal Pod Autoscaler"
                  properties:
                    scaleTargetRef:
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                    minReplicas:
                      type: integer
                    maxReplicas:
                      type: integer
                    metrics:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          resource:
                            type: object
                            properties:
                              name:
                                type: string
                              target:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  averageUtilization:
                                    type: integer
                                  averageValue:
                                    type: string
                vpa:
                  type: object
                  description: "Embedded full spec of Vertical Pod Autoscaler"
                  properties:
                    targetRef:
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                    updatePolicy:
                      type: object
                      properties:
                        updateMode:
                          type: string
                    resourcePolicy:
                      type: object
                      properties:
                        containerPolicies:
                          type: array
                          items:
                            type: object
                            properties:
                              containerName:
                                type: string
                              minAllowed:
                                type: object
                                additionalProperties:
                                  type: string
                              maxAllowed:
                                type: object
                                additionalProperties:
                                  type: string
  scope: Namespaced
  names:
    plural: oblikpodautoscalers
    singular: oblikpodautoscaler
    kind: OblikPodAutoscaler
    shortNames:
      - opa
