---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oblik-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oblik-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["autoscaling.k8s.io", "autoscaling"]
    resources: ["verticalpodautoscalers", "horizontalpodautoscalers"]
    verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]
  - apiGroups: ["socialgouv.io"]
    resources: ["oblikpodautoscalers"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oblik-operator
subjects:
  - kind: ServiceAccount
    name: oblik-operator
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: oblik-operator
  apiGroup: rbac.authorization.k8s.io
---

