{{ if .Values.genVpa.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: gen-vpa
spec:
  background: true
  generateExisting: true
  useServerSideApply: true
  rules:
    - name: create-vpa
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - CronJob
                # - Rollout
      context:
        - name: annotations
          variable:
            jmesPath: request.object.metadata.annotations
            default: {}
        - name: oblikEnabled
          variable:
            jmesPath: request.object.metadata.annotations."oblik.socialgouv.io/enabled"
            default: "false"
      generate:
        apiVersion: autoscaling.k8s.io/v1
        kind: VerticalPodAutoscaler
        name: "vpa-{{`{{ (request.object.kind == 'Deployment' && 'deployment') || (request.object.kind == 'StatefulSet' && 'statefulset') || (request.object.kind == 'CronJob' && 'cronjob') || (request.object.kind == 'Rollout' && 'rollout') }}`}}-{{`{{request.object.metadata.name}}`}}"
        namespace: "{{`{{request.namespace}}`}}"
        synchronize: true
        data:
          metadata:
            annotations: '{{"{{ annotations }}"}}'
            labels:
              oblik.socialgouv.io/enabled: "{{`{{ oblikEnabled  }}`}}"
          spec:
            targetRef:
              apiVersion: "{{`{{request.object.apiVersion}}`}}"
              kind: "{{`{{request.object.kind}}`}}"
              name: "{{`{{request.object.metadata.name}}`}}"
            updatePolicy:
              updateMode: "Off"
{{ end }}