replicas: 3

image:
  repository: ghcr.io/socialgouv/oblik
  tag: 
  pullPolicy: 

webhook:
  enabled: true
  failurePolicy: Fail # Fail or Ignore

# Additional arguments to pass to the operator
args: []
# Example:
# args:
#   - "-v=2"  # Enable debug logging
#   - "-v=3"  # Enable verbose debug logging

env: {}

existingSecret: 

resources: {}

annotations: {}
