replicas: 3

image:
  repository: ghcr.io/socialgouv/oblik
  tag: 
  pullPolicy: 

webhook:
  enabled: true
  failurePolicy: Fail # Fail or Ignore

# Additional arguments to pass to the operator
args: []
# Example:
# args:
#   - "-v"     # Verbosity flag
#   - "2"      # Debug logging level
#   - "-v"     # Or for more verbose logging:
#   - "3"      # Verbose debug logging level

env: {}

existingSecret: 

resources: {}

annotations: {}
