replicas: 3

image:
  repository: ghcr.io/socialgouv/oblik
  tag: 
  pullPolicy: 

webhook:
  enabled: true
  failurePolicy: Fail # Fail or Ignore

# Additional arguments to pass to the operator
args: []
# Example:
# args:
#   - "-v"  # Verbosity level (0-4)
#   - "2"   # 0=info, 2=debug, 3=verbose debug

env: {}

existingSecret: 

resources: {}

# Pod Disruption Budget configuration
pdb:
  enabled: true
  # Either minAvailable or maxUnavailable should be set, not both
  minAvailable: 2  # Ensure at least 2 pods are always available
  # maxUnavailable: 1  # Alternative: allow at most 1 pod to be unavailable

annotations: {}
