name: 👾 Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  makefile-lint:
    name: Makefile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: Add Go bin to PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Install linter
        run: make install-lint-tools
      - name: Run linter
        run: make lint