name: ✔️ Tests E2E

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.0'

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Run E2E tests
      run: |
        ./tests/e2e.sh