name: ✔️ Tests E2E
concurrency:
  cancel-in-progress: true
  group: tests-e2e-${{ github.ref_name }}

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Install Kind
      uses: devthefuture-org/kind-with-registry-action@main
      with:
        kind_version:    v0.24.0
        kubectl_version: v1.30.0
        ingress_enabled: false
        registry_image:  registry:2
        node_image:      kindest/node:v1.30.0

    - name: Run E2E tests
      shell: bash
      run: |
        set -eo errexit
        export KUBECONFIG="${HOME}/.kube/config"
        ./tests/install-dependencies.sh
        ./tests/deploy-oblik.sh
        ./tests/test-oblik.sh -v
